name: Deploy form

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Merge JSONSCHEMA
        run: |
          pip3 install jsonschema pyyaml json-schema-for-humans
          python3 validate merge-to-json
          cd form/public/
          generate-schema-doc schema.json

      - name: Build form app
        run: |
          cd form/
          yarn install
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./form/build
